### ISSUE TITLE
error does not exist table icesheet_polygons.

### ISSUE THREAD

**Issue by smja1376** [gravitystorm/openstreetmap-carto#4245]
Hi to everyone.
i when lunch server give this errors:( 
```
renderd[44150]: An error occurred while loading the map layer 'ajt': Postgis Plugin: ERROR:  relation "icesheet_polygons" does not exist
LINE 1: SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "...
                                           ^
in executeQuery Full sql was: 'SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "way" IS NOT NULL LIMIT 1;'
  encountered during parsing of layer 'icesheet-poly' in Layer at line 5895 of '/home/""/src/openstreetmap-carto/mapnik.xml'
renderd[44150]: An error occurred while loading the map layer 'ajt': Postgis Plugin: ERROR:  relation "icesheet_polygons" does not exist
LINE 1: SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "...
                                           ^
in executeQuery Full sql was: 'SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "way" IS NOT NULL LIMIT 1;'
  encountered during parsing of layer 'icesheet-poly' in Layer at line 5895 of '/home/""/src/openstreetmap-carto/mapnik.xml'
renderd[44150]: An error occurred while loading the map layer 'ajt': Postgis Plugin: ERROR:  relation "icesheet_polygons" does not exist
LINE 1: SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "...
                                           ^
in executeQuery Full sql was: 'SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "way" IS NOT NULL LIMIT 1;'
  encountered during parsing of layer 'icesheet-poly' in Layer at line 5895 of '/home/""/src/openstreetmap-carto/mapnik.xml'renderd[44150]: An error occurred while loading the map layer 'ajt': Postgis Plugin: ERROR:  relation "icesheet_polygons" does not exist
LINE 1: SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "...
                                           ^
in executeQuery Full sql was: 'SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "way" IS NOT NULL LIMIT 1;'
  encountered during parsing of layer 'icesheet-poly' in Layer at line 5895 of '/home/""/src/openstreetmap-carto/mapnik.xml'
```
and by run **scripts/get-external-data.py** give this errors.
```
INFO:root:Checking table simplified_water_polygons
INFO:root:Table simplified_water_polygons did not require updating
INFO:root:Checking table water_polygons
Traceback (most recent call last):
  File "scripts/get-external-data.py", line 258, in <module>
    main()
  File "scripts/get-external-data.py", line 251, in main
    this_table.index()
  File "scripts/get-external-data.py", line 71, in index
    cur.execute('''ALTER TABLE "{temp_schema}"."{name}" SET ( autovacuum_enabled = FALSE );'''
psycopg2.errors.UndefinedTable: relation "loading.water_polygons" does not exist
```

**Comment by pnorman** [comment]
What version of gdal do you have on your local machine, and what version of PostgreSQL are you connecting to?

**Comment by smja1376** [comment]
gdal version: 3.0.4
PostgreSQL  last version.

**Comment by syncush** [comment]
I can confirm that `get-external-data.py` works on PostgresSQL <=11 but does not work on PostgresSQL 12.
Haven't tested on PostgresSQL 13

**Comment by SomeoneElseOSM** [comment]
I wonder if what's happening here is the same as https://github.com/gravitystorm/openstreetmap-carto/issues/4249 ?  ne_110m_admin_0_boundary_lines_land.zip has moved and is now at https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip ; as a temporary workaround you can try changing the URL in get_external_data.yml , rerun "scripts/get_external_data.py" and see if everything then works?

**Comment by SomeoneElseOSM** [comment]
For info, I've just closed https://github.com/gravitystorm/openstreetmap-carto/issues/4249 (which this shows the same symptoms as).  Perhaps just try retesting?

**Comment by pnorman** [comment]
@smja1376 Do you still experience this issue?
