### ISSUE TITLE
psycopg2.errors.UndefinedTable: relation "loading.water_polygons" does not exist

### ISSUE THREAD

**Issue by johnriedel** [gravitystorm/openstreetmap-carto#4335]
### Expected behavior
No Python exception is expected.

### Actual behavior
Ubuntu 20.04.2 LTS
python3/focal,now 3.8.2-0ubuntu2 amd64
python3-yaml/focal,now 5.3.1-1 amd64
python3-psycopg2/focal,now 2.8.4-2 amd64
python3-zipp/focal,now 1.0.0-1 all
python3-requests/focal,now 2.22.0-2ubuntu1 all

When executing "scripts/get-external-data.py", the following occurs:
INFO:root:Checking table simplified_water_polygons
INFO:root:Checking table water_polygons
Traceback (most recent call last):
  File "scripts/get-external-data.py", line 294, in <module>
    main()
  File "scripts/get-external-data.py", line 284, in main
    this_table.index()
  File "scripts/get-external-data.py", line 77, in index
    cur.execute('''ALTER TABLE "{temp_schema}"."{name}" SET ( autovacuum_enabled = FALSE );'''
psycopg2.errors.UndefinedTable: relation "loading.water_polygons" does not exist

**Comment by johnriedel** [comment]
Verbose output:
$ scripts/get-external-data.py --verbose
INFO:root:Checking table simplified_water_polygons
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): osmdata.openstreetmap.de:443
DEBUG:urllib3.connectionpool:https://osmdata.openstreetmap.de:443 "GET /download/simplified-water-polygons-split-3857.zip HTTP/1.1" 200 23636978
DEBUG:root:running ogr2ogr -f PostgreSQL -lco GEOMETRY_NAME=way -lco SPATIAL_INDEX=FALSE -lco EXTRACT_SCHEMA_FROM_LAYER_NAME=YES -nln loading.simplified_water_polygons PG:dbname=gis data/simplified_water_polygons/simplified-water-polygons-split-3857/simplified_water_polygons.shp
INFO:root:Checking table water_polygons
DEBUG:urllib3.connectionpool:https://osmdata.openstreetmap.de:443 "GET /download/water-polygons-split-3857.zip HTTP/1.1" 200 749335400
DEBUG:root:running ogr2ogr -f PostgreSQL -lco GEOMETRY_NAME=way -lco SPATIAL_INDEX=FALSE -lco EXTRACT_SCHEMA_FROM_LAYER_NAME=YES -nln loading.water_polygons PG:dbname=gis data/water_polygons/water-polygons-split-3857/water_polygons.shp
Traceback (most recent call last):
  File "scripts/get-external-data.py", line 294, in <module>
    main()
  File "scripts/get-external-data.py", line 284, in main
    this_table.index()
  File "scripts/get-external-data.py", line 77, in index
    cur.execute('''ALTER TABLE "{temp_schema}"."{name}" SET ( autovacuum_enabled = FALSE );'''
psycopg2.errors.UndefinedTable: relation "loading.water_polygons" does not exist

**Comment by johnriedel** [comment]
This issue was caused by my Linux container running out of storage space. Closing issue.

$ ogr2ogr -f PostgreSQL -lco GEOMETRY_NAME=way -lco SPATIAL_INDEX=FALSE -lco EXTRACT_SCHEMA_FROM_LAYER_NAME=YES -nln loading.water_polygons PG:dbname=gis data/water_polygons/water-polygons-split-3857/water_polygons.shp
Warning 6: 'FALSE' is an unexpected value for SPATIAL_INDEX layer creation option of type string-select.
ERROR 1: COPY statement failed.
ERROR:  could not extend file "base/16385/56401": No space left on device
HINT:  Check free disk space.
CONTEXT:  COPY water_polygons, line 1710
