### ISSUE TITLE
Kosmtik preview fails with 'Project not loaded properly'

### ISSUE THREAD

**Issue by tajchert** [gravitystorm/openstreetmap-carto#4360]
When I run:
`kosmtik serve ./project.mml`

I should see Kosmtik preview of this style, however currently I'm getting:
```
[httpserver] /openstreetmap-carto/tile/4/4/6.png?t=1617639153488 500
Trace
    at ProjectServer.raise (/usr/local/lib/node_modules/kosmtik/src/back/ProjectServer.js:261:13)
    at ProjectServer.serveTile (/usr/local/lib/node_modules/kosmtik/src/back/ProjectServer.js:67:14)
    at tile (/usr/local/lib/node_modules/kosmtik/src/back/ProjectServer.js:50:108)
    at Project.StateBase.when (/usr/local/lib/node_modules/kosmtik/src/back/StateBase.js:51:33)
    at ProjectServer.serve (/usr/local/lib/node_modules/kosmtik/src/back/ProjectServer.js:50:70)
    at PreviewServer.forwardToProject (/usr/local/lib/node_modules/kosmtik/src/back/PreviewServer.js:74:23)
    at PreviewServer.serve (/usr/local/lib/node_modules/kosmtik/src/back/PreviewServer.js:68:42)
    at Server.emit (events.js:180:13)
    at parserOnIncoming (_http_server.js:642:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
Project not loaded properly.
```
And no preview is rendered.

My versions:
- Latest Kosmtik (with Mapnik 3.0.20 but 3.0.0 gives the same issue)
- Node 9.11.2
- npm 5.6.0
- `openstreetmap-carto` 5.3.1 (latest, without any changes)

I used with no problem same version and Kosmtik with this [style (CartoDB positron)](https://github.com/CartoDB/basemap-styles/tree/master/cartocss/web-styles/positron.tm2) and it rendered without any issues, so it seems more like carto style related than Kosmtik itself but there is still open issue of https://github.com/kosmtik/kosmtik/issues/263

**Comment by tajchert** [comment]
Installing all [Noto fonts](https://www.google.com/get/noto/) from and then explicitly  `Noto Sans Tibetan` 
kind of solved it, now the output is:
```
[httpserver] /openstreetmap-carto/tile/4/11/6.png?t=1617640387843 500
Trace
    at ProjectServer.raise (/usr/local/lib/node_modules/kosmtik/src/back/ProjectServer.js:261:13)
    at /usr/local/lib/node_modules/kosmtik/src/back/ProjectServer.js:75:30
    at /usr/local/lib/node_modules/kosmtik/node_modules/generic-pool/lib/generic-pool.js:283:11
    at loaded (/usr/local/lib/node_modules/kosmtik/node_modules/mapnik-pool/index.js:23:37)
Postgis Plugin: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
Connection string: ' dbname=gis connect_timeout=4'
  encountered during parsing of layer 'landcover-low-zoom' in Layer
[httpserver] /openstreetmap-carto/tile/4/4/9.png?t=1617640387843 500
```

**Comment by tajchert** [comment]
Ok, I used Kosmtik in Docker and it works without issue. I'm closing this.
If you have similar issues - take a look here and use Docker - https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

**Comment by 2803media** [comment]
hello @tajchert I use the switch2osm tutorial to set up the tile server but I want to use the cartodb positron stylesheet, could you explain how you do it please?

**Comment by pnorman** [comment]
> hello @tajchert I use the switch2osm tutorial to set up the tile server but I want to use the cartodb positron stylesheet, could you explain how you do it please?

This is the OpenStreetMap Carto issue tracker, your question doesn't involve OpenStreetMap Carto.

**Comment by 2803media** [comment]
> > hello @tajchert I use the switch2osm tutorial to set up the tile server but I want to use the cartodb positron stylesheet, could you explain how you do it please?
> 
> This is the OpenStreetMap Carto issue tracker, your question doesn't involve OpenStreetMap Carto.

Sure it is I want to use OpenStreetMap Carto with the positron style not the classic mapnik.xml
