### ISSUE TITLE
scripts/get-external-data.py does not work with psycopg2 2.9.1

### ISSUE THREAD

**Issue by cbluoss** [gravitystorm/openstreetmap-carto#4447]
### Expected behavior
Script runs smoothly as expected (and how it did with psycopg2==2.8.6)
### Actual behavior
Script crashes 
```
INFO:root:Checking table simplified_water_polygons
Traceback (most recent call last):
  File "scripts/get-external-data.py.1", line 108, in index
    cur.execute('''VACUUM ANALYZE "{temp_schema}"."{name}";'''
psycopg2.errors.ActiveSqlTransaction: VACUUM cannot run inside a transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/get-external-data.py.1", line 294, in <module>
    main()
  File "scripts/get-external-data.py.1", line 284, in main
    this_table.index()
  File "scripts/get-external-data.py.1", line 111, in index
    self._conn.autocommit = old_autocommit
psycopg2.ProgrammingError: set_session cannot be used inside a transaction
```

**Comment by mboeringa** [comment]
May be related to this issue and the associated changes in 2.9.0:

https://github.com/psycopg/psycopg2/issues/941

See the first point in the release notes of 2.9.0:

https://github.com/psycopg/psycopg2/releases/tag/2_9
