### ISSUE TITLE
Make get-external-data.py search relative to itself for external-data.yml

### ISSUE THREAD

**Issue by pnorman** [gravitystorm/openstreetmap-carto#4892]
When installing a server I noticed that get-external-data.py needs to be run from the osm-carto directory.

```sh
$ sudo -u _renderd /home/_renderd/openstreetmap-carto/scripts/get-external-data.py
INFO:root:Starting load of external data into database
Traceback (most recent call last):
  File "/home/_renderd/openstreetmap-carto/scripts/get-external-data.py", line 405, in <module>
    main()
  File "/home/_renderd/openstreetmap-carto/scripts/get-external-data.py", line 288, in main
    with open(opts.config) as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'external-data.yml'
```

The work-around is to switch directories, but this should not be necessary. The script should look relative to its location, not the current working directory.

**Comment by imagico** [comment]
We have, in general, not been consistent in that regard with our scripts:

* `get-external-data.py` - needs to be run from main directory
* `generate_road_colours.py` - needs to be run from main directory
* `generate_unpaved_patterns.py` - needs to be run from main directory
* `get-fonts.sh` - needs to be run from main directory
* `change-fonts-cjk.sh` - needs to be run from main directory
* `generate_shields.py` - operates relative to script location
* `indexes.py` - operates relative to script location
